### ISSUE TITLE
Unable to save authtoken

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [khiemdoan/ngrok-snap#1]
```
$ ngrok authtoken _secret_token_

ERROR:  Failed to save authtoken to configuration file '/home/buo.ren.lin/.ngrok2/ngrok.yml': mkdir /home/buo.ren.lin/.ngrok2: permission denied
```

This is due to the fact that the `home` confinement interface doesn't allow access to the dotfiles right under the user's home directory, a possible solution is to request a grant to use the `~/.ngrok2` directory via the `personal-files` confinement interface.

**Comment by Fantus** [comment]
would be nice to see this fixed

**Comment by NicoHaase** [comment]
Are there any news on this topic?

**Comment by polarising-aferreira** [comment]
I'm also having the same problem on ubuntu 18.04

**Comment by davidstrouksf** [comment]
Hi, I'm also getting this issue on Ubuntu 18.04

**Comment by scythargon** [comment]
+1

**Comment by cklosowski** [comment]
I'm also running into this issue with the snap install on Ubuntu 19.04.

**Comment by khiemdoan** [comment]
Please vote for me at [Personal-files request for ngrok](https://forum.snapcraft.io/t/personal-files-request-for-ngrok/13511)

**Comment by NicoHaase** [comment]
> Please vote for me at [Personal-files request for ngrok](https://forum.snapcraft.io/t/personal-files-request-for-ngrok/13511)

While I'm definitly in favor of voting for it, can you answer the question of Alex posted on snapcraft one week ago?

**Comment by ksob** [comment]
snap install ngrok --devmode

installing in devmode fixes this

**Comment by secretshardul** [comment]
It is 2023 but `snap install ngrok --devmode` is still needed

**Comment by CK-Ward** [comment]
@secretshardul can you try again? `snap install ngrok` gives me this successful output: 
```ngrok (v3/stable) 3.3.5 from Kyle Wenholz (kyle-ngrok) installed```

**Comment by secretshardul** [comment]
> @secretshardul can you try again? `snap install ngrok` gives me this successful output: `ngrok (v3/stable) 3.3.5 from Kyle Wenholz (kyle-ngrok) installed`

```
ngrok http 3000

ERROR:  Error reading configuration file '/home/hp/.config/ngrok/ngrok.yml': open /home/hp/.config/ngrok/ngrok.yml: permission denied
```

Still same problem. I'm running on Lubuntu 23.04 (an Ubuntu flavor)

**Comment by CK-Ward** [comment]
@secretshardul Looks like you don't have read permissions on that directory or file, you'll need to `chmod` the appropriate directory/file to get it to work: https://www.pluralsight.com/blog/it-ops/linux-file-permissions
