### ISSUE TITLE
ngrok would like to publish directly to Snap

### ISSUE THREAD

**Issue by krwenholz** [khiemdoan/ngrok-snap#5]
Hi @khiemdoan!

I work at ngrok. First, thank you so much for making ngrok available on Snap.

We'd like to start publishing our releases directly to Snap. It seems you own the app named `ngrok` right now. We'd love to help out by taking ownership of the app on Snap so we can publish with every new release. Is this something you could help us with? If transferring app ownership is too difficult, perhaps we could change the current app name to something like `ngrok-community` and ngrok could take the `ngrok` name?

Let us know what we can do and thank you again for making ngrok more available.

**Comment by khiemdoan** [comment]
Hi @krwenholz,

I totally agree to transfer the ownership to you. You don't need to create another `ngrok` on Snap, it will make people confuse. I am also very happy if you mention me in the description on Snap :blush: :blush:

**Comment by krwenholz** [comment]
We'd be happy to give some credit where it's due! Thank you so much.

I've created an Ubuntu one account with my work email (kyle-ngrok). Is there anything I need to do on our end? We're not very familiar with Snap yet, so any guidance would be appreciated. (The docs were unclear how package ownership works.)

**Comment by khiemdoan** [comment]
You just need to login and submit this form. Do follow the instructions of the website.

[https://snapcraft.io/register-name-dispute?snap-name=ngrok](https://snapcraft.io/register-name-dispute?snap-name=ngrok)

**Comment by krwenholz** [comment]
Thank you! I'll start that process. Not sure why I couldn't find that earlier.

**Comment by Roadmaster** [comment]
Hi folks,

I've performed the transfer as requested and with the current owner's approval here.

Note that the previous owner (khiemdoan) still has collaborator privileges (added automatically during the snap transfer process). The new owner can remove the "share" if that is not desired.

Feel free to poke me here on github or preferrably ask generally in https://forum.snapcraft.io if there are any questions or comments!

**Comment by krwenholz** [comment]
Thanks @Roadmaster!

@khiemdoan we'll have to remove your collaborator privileges in a bit, but we're going to put your name in the README and have decided to use a forked version of the original repository. Thank you so much for your contributions.
